apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testnet
resources:
  - ../../templates/flo-explorer
  - managed-cert.yaml
  - ingress.yaml
patchesStrategicMerge:
  - configmap.yaml
  - flo-explorer-storage.yaml